version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: oboi_best
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432' # Пробрасываем порт 5432 контейнера на порт 5434 хоста
    volumes:
      - postgres_data:/var/lib/postgresql/data # Монтирование тома для сохранения данных

volumes:
  postgres_data:
